export const INCREMENT_CP_PLAYER_1 = "INCREMENT_CP_PLAYER_1";
export const DECREASE_CP_PLAYER_1 = "DECREASE_CP_PLAYER_1";

export const INCREMENT_CP_PLAYER_2 = "INCREMENT_CP_PLAYER_2";
export const DECREASE_CP_PLAYER_2 = "DECREASE_CP_PLAYER_2";

export const INCREMENT_BATTLEROUND = 'INCREMENT_BATTLEROUND';
export const DECREASE_BATTLEROUND = 'DECREASE_BATTLEROUND';